[versions]
core = "1.6.1"
junitJupiter = "5.11.2"
material = "1.3.0"
kotlin = "2.1.10"
sonarQube = "5.1.0.4882"
jacoco = "0.8.12"
androidLibrary = "8.6.1"
jfrog = "5.2.5"
compose = "1.7.4"
sdp-ssp = "1.0.5"

[libraries]
##UI
androidx-compose = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material" }
androidx-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }

##Test cases
androidx-core = { module = "androidx.test:core", version.ref = "core" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
androidx-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-test-manifest =  { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
sdp-android = { module ="com.intuit.sdp:sdp-android", version.ref = "sdp-ssp" }
ssp-android = { module= "com.intuit.ssp:ssp-android", version.ref = "sdp-ssp" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "androidLibrary" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref= "kotlin"}
jfrogArtifactory = { id = "com.jfrog.artifactory", version.ref = "jfrog" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
